# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 03:12
from __future__ import unicode_literals

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normalusers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='follower',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u4fdd\u5b58\u65e5\u671f'),
        ),
    ]
