# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-12 05:43
from __future__ import unicode_literals

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('normalusers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentC',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=140)),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u4fdd\u5b58\u65e5\u671f')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_cc_name', to='normalusers.User')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_c_name', to='normalusers.User')),
            ],
        ),
        migrations.CreateModel(
            name='CommentP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=140)),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u4fdd\u5b58\u65e5\u671f')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_c_name', to='normalusers.User')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_name', to='normalusers.User')),
            ],
        ),
        migrations.CreateModel(
            name='ForwardP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=140)),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u4fdd\u5b58\u65e5\u671f')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_f_name', to='normalusers.User')),
            ],
        ),
        migrations.CreateModel(
            name='LikeP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u4fdd\u5b58\u65e5\u671f')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author_l_name', to='normalusers.User')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_name', to='normalusers.User')),
            ],
        ),
        migrations.CreateModel(
            name='Poster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_type', models.IntegerField()),
                ('text', models.CharField(max_length=140)),
                ('forward_num', models.IntegerField(default=0)),
                ('comment_num', models.IntegerField(default=0)),
                ('like_num', models.IntegerField(default=0)),
                ('collect_num', models.IntegerField(default=0)),
                ('time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='\u4fdd\u5b58\u65e5\u671f')),
                ('origin_poster_id', models.IntegerField(default=0)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poster', to='normalusers.User')),
            ],
        ),
        migrations.AddField(
            model_name='likep',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='like_p', to='poster.Poster'),
        ),
        migrations.AddField(
            model_name='forwardp',
            name='f_poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forward_f_p', to='poster.Poster'),
        ),
        migrations.AddField(
            model_name='forwardp',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forward_name', to='normalusers.User'),
        ),
        migrations.AddField(
            model_name='forwardp',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forward_p', to='poster.Poster'),
        ),
        migrations.AddField(
            model_name='commentp',
            name='poster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_p', to='poster.Poster'),
        ),
        migrations.AddField(
            model_name='commentc',
            name='originComment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_c', to='poster.CommentP'),
        ),
    ]
